### ISSUE TITLE
Debian client instructions please!

### ISSUE THREAD

**Issue by zenitogr** [digitalocean/marketplace-pi-hole-vpn#10]
Ok found out how.

just copy paste it in /etc/wireguard/wg0.conf

Original:
All the guides I see about Debian Client setup are incoprenhensible based on the given config from regen-vpn-keys.sh!!!

what do I add to the /etc/wireguard/wg0.conf?

or how do I add the output of the regen-vpn-keys output config to Debian wireguard client? thank you

**Comment by CrashenX** [comment]
Yep! Glad you got it figured out. Sorry for not seeing this sooner!
