### ISSUE TITLE
accessing pihole admin interface

### ISSUE THREAD

**Issue by TetteDev** [digitalocean/marketplace-pi-hole-vpn#13]
do I have to manually setup this or is it already included in the script? I cannot seem to access the pihole admin interface from accessing http://<my reserved droplet ip>/admin/index.php

**Comment by CrashenX** [comment]
@Sadulisten Connect to the full vpn. Then go to `http://pi.hole/admin`. You can change the password of the admin interface by sshing into Droplet and running `pihole -a -p`
