### ISSUE TITLE
IPv6 problem

### ISSUE THREAD

**Issue by fredgit12** [digitalocean/marketplace-pi-hole-vpn#8]
I run against the droplet with IPv6 enabled, it doesn't work. but the droplet with no IPv6 works fine.

**Comment by CrashenX** [comment]
@fredgit12 Is your client using IPV6, see: https://github.com/digitalocean/marketplace-pi-hole-vpn/blob/main/scripts/wg-setup.sh#L180-L184

The wireguard client configuration specifies the server IP and port. If you create a Droplet with IPV6 enabled it uses the IPV6 address in the client config and the client must support IPV6. You can manually update the client config to specify the IPV4 address on the clients that do not support IPV6, and that will solve the issue.

Not all networks support IPV6. For instance, on your home network and your mobile provider network IPV6 might be enabled, but not on an open access point you connect to. Unless you need IPV6, you'll probably have less headaches if you don't enable it for this use case.
