### ISSUE TITLE
can't connect with pc

### ISSUE THREAD

**Issue by MasterBrian99** [digitalocean/marketplace-pi-hole-vpn#9]
after successful installation,i was able to connect with android phone and see admin interface with [http://pi.hole/admin](http://pi.hole/admin)  and everything work perfectly. but when i tried to connect with pc pi-hole not working correctly. on pc (Arch Linux) it only work vpn connection.traffic not routing with pi hole. 
i've tried many methods  ([wireguard-tools](https://archlinux.org/packages/?name=wireguard-tools), [https://github.com/Devsfy/wiregui](https://github.com/Devsfy/wiregui))  to connect but  same result.

**Comment by CrashenX** [comment]
@MasterBrian99 Did you use the the [regen-vpn-keys script](https://github.com/digitalocean/marketplace-pi-hole-vpn/blob/main/scripts/wg-setup.sh#L187-L199) (see lines 187-199 which are written to the README in the Droplet) to generate 2 client configs (one for mobile, one for linux pc) or are you trying to use the same config on both devices?

**Comment by MasterBrian99** [comment]
i read the scripts and created new clients.somehow after little bit of tweaking i found out my pc was the problem.my ip tables were all wrong.unstable packages and so many things.most importantly i forgot about my [hblock](https://github.com/hectorm/hblock)  block list .now it works perfectly.. 🤗.

**Comment by CrashenX** [comment]
@MasterBrian99 Amazing! Glad you got it working!
